version: '2'
services:
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  worker:
    image: node:9-onbuild
    volumes:
      - ./worker:/usr/src/app
    restart: always
    environment:
      - MONGODB=mongodb://db/routes
      - TIME_INTERVAL=5000
      - GOOGLE_MAPS_API_KEY=
    links:
      - db
    depends_on:
      - db
  api:
    image: node:9-onbuild
    volumes:
      - ./api:/usr/src/app
    restart: always
    environment:
      - NODE_PORT=80
      - MONGODB=mongodb://db/routes
    expose:
      - "80"
    links:
      - db
    depends_on:
      - db
  haproxy:
    image: dockercloud/haproxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    links:
      - api